language: python
install:
  - pip install -r requirements.txt
script:
  - flake8 .
addons:
  sonarcloud:
    organization: "adzhukov"
script:
  - sonar-scanner
  - pytest --cov || true
after_success:
  coveralls
