language: python
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - flake8 .
addons:
  sonarcloud:
    organization: "adzhukov"
script:
  - sonar-scanner
after_success:
  coveralls
